### ISSUE TITLE
can not load text or json file

### ISSUE THREAD

**Issue by Fusyong** [littlee/wechat-small-game-phaser#3]
Hi,
I can not load a text or json file but do a image, which in the same directory.

errors as follow:
VM3449:1 request:fail invalid url "test.json"
VM3449:1 Phaser.Loader - json[test]: error loading asset from URL test.json

**Comment by littlee** [comment]
@Fusyong can you provide some snippet of you code ?

**Comment by littlee** [comment]
@Fusyong Maybe I've known what your problem is.
```js
this.load.json('data', './data.json');
// request:fail invalid url "./data.json"
```

Loading JSON with a relative path won't work, because it's different from loading a image.
So you have to put you json file on the server and load it with a URL.

```js
this.load.json('data', 'http://phaser.io/version.json'); // works !!!
```

P.S.
Difference between loading image and loading JSON
when loading image, Phaser is doing something like
```js
var img = new Image();
img.src ='./path/to/img.png';
```
so relative path will be fine.

but when loading JSON, Phaser has to make a Ajax request behind, which will call `wx.request` (with the help of the adapter), and `wx.request` accepts valid URL string only.

**Comment by Fusyong** [comment]
Thanks！

**Comment by Fusyong** [comment]
@littlee Thank you very much for the details.
